### PR TITLE
Update and rename dangae.py to dannotgae.py

### PR DESCRIPTION
**Pull request by Dan3a**

### CODE REVIEW

**Comment by LosWheatleynDew** [comment]
still gae

**Comment by Dan3a** [comment]
I contest that

**Comment by Dan3a** [comment]
Objection!

**Comment by LosWheatleynDew** [comment]
@Mar0xy do you support or no

**Review by Mar0xy — COMMENTED** [review]
This is bad

**Comment by Mar0xy** [comment]
keep this closed

**Comment by Dan3a** [comment]
I'm not happy

**Comment by Mar0xy** [comment]
> I'm not happy

dont care

**Pull request closed without merging**
